/**************************************************************************
 * Contains the register bitfield mode settings.
 *
 * This file was generated by dclib/netpp. Modifications to this file will
 * be lost.
 * Stylesheet: values.xsl       (c) 2004-2014 section5.ch
 *
 * Version: 0.0develop
 *
 **************************************************************************/

#ifndef _BFM_
#define _BFM_(x, n)  ( ((x) << n##_SHFT) & (n))
#endif


/* 'Add_W2': #OpcodeRes::ADD_W2 */
	
#define ADD_W2_NULL                             _BFM_(0, ADD_W2)
#define ADD_W2_PLUS2                            _BFM_(1, ADD_W2)
#define ADD_W2_MINUS2                           _BFM_(2, ADD_W2)

